USE nursing_training;

INSERT INTO Hospitals (name, address) VALUES
('Late Matoshri Ramabai Ambedkar Maternity Home, AmbilOdha', 'kasba - vishrambagwada WO, Ambil Odha, Pune'),
('Aundh Kuti Maternity Home, Aundh', 'Aundh - Baner WO, Aundh, Pune'),
('Late Draupadabai Murlidhar Khedekar Maternity Home, Bopodi', 'Aundh - Baner WO, Bopodi, Pune'),
('Dr. Dalvi, PMC Joint Project', 'Ghole Road - Shivaji Nagar WO, Shivaji Nagar Station, Pune'),
('Late Anna Saheb Magar Maternity Home, Hadapsar', 'Hadapsar - Mundhwa WO, Hadapsar, Pune'),
('Dr. Homi J. Bhabha Maternity Home, Health Camp', 'Ghole Road - Shivaji Nagar WO, Health Camp, Pune'),
('Late Jayabai Sutar Maternity Home, Kothrud', 'Kothrud - Bavdhan WO, Gujrath Colony, Kothrud, Pune'),
('Late Sakharam Kundalik Kodre Maternity Home, Mundhwa', 'Hadapsar - Mundhwa WO, Mundhwa, Pune'),
('Late Sahadev Eknath Nimhan Maternity Home, Pashan', 'Aundh - Baner WO, Pashan Gaon, Pune'),
('Late Chandu Mama Sonawane Maternity Home', 'Bhawani Peth WO, Bhawani Peth, Pune'),
('Late Namedevrao Shivarkar Maternity Home, Wanorie', 'Wanowrie - Ramtekdi WO, Wanowrie, Pune'),
('Bharatratna Rajiv Gandhi Hospital, Yerawada', 'Sangamwadi WO, Yerawada, Pune'),
('Late Savitribai Phule Maternity Home, Guruwarpeth', 'Bhawani Peth WO, Guruwar Peth, Pune'),
('Late Minatai Thakare Maternity Home, Kondhwa', 'Kondhwa - Yewlewadi WO, Kondhwa, Pune'),
('Late Malti Kachi Maternity Home, Gadikhana', 'kasba - vishrambagwada WO, Gadikhana, Shukruwar Peth, Pune'),
('Rajmata Jijau Mitra Mandal (only IPD)', 'kasba - vishrambagwada WO, Mitramandal, Pune'),
('Late Kashinath Aa. Dhankavde, Balajinagar', 'Kondhwa - Yewlewadi WO, Balaji Nagar, Pune'),
('Chatrpati Shivray Disp, Yerwada, Nagpur Chawl', 'Sangamwadi WO, Maharashtra Housing Board, Yerawada, Pune'),
('Kamla Nehru Hospital', 'Bhawani Peth WO, Somwar Peth, Pune'),
('Dr. Naidu Infectious Disease Hospital', 'Dhole Patil Road WO, Pune Station, Pune'),
('Late. Tharkude Dispensary, Erandwane', 'Warje - Karve Nagar WO, Erandwane, Pune'),
('Bai Bhikaji Pastonji Bammanji Dispensary, Bhawanipeth', 'Bhawani Peth WO, Bhawani Peth, Pune'),
('Late Anandibai Narhar Gadgil Dispensary, Dattawadi', 'Sinhagad Road WO, Dattawadi, Pune'),
('Late Balaji Rakhmaji Gaikwad Dispensary, Ganjpeth', 'Bhawani Peth WO, Ganjpeth, Pune'),
('Late Vijayabai Shirke Health Centre, Hingne', 'Warje - Karve Nagar WO, Hingne, Pune'),
('Hindu Samrat SS Pramukh Balasaheb Thakare Disp, Parvati Darshan / old Lions Club Dispensary, Mitra Mandal', 'kasba - vishrambagwada WO, Mitramandal, Pune'),
('Late Dada Saheb Gaikwad Dispensary, Mangalwarpeth, Barne Road', 'Bhawani Peth WO, Mangalwar Peth, Pune'),
('Late Kalawati Mawale Dispensary, Narayanpeth', ', Narayan Peth, Pune'),
('Late Mama Saheb Badade Dispensary, Nanapeth', 'Bhawani Peth WO, Nana Peth, Pune'),
('Hutatama Babu Genu Dispensary, Raviwarpeth', ', Ravivar Peth, Pune'),
('Siddharth Dispensary, Vishrantwadi', ', Vishrantwadi, Pune'),
('Late Shivshankar Pote Dispensary, Sahakarnagar', 'Sahakar Nagar - Dhankawadi WO, Sahakar Nagar, Pune'),
('Late Mukundrao Lele Dispensary, Shaniwarpeth', ', Shaniwar Peth, Pune'),
('Late Jangalrao Kondiba Amrale Dispensary, Shivaji Nagar', ', PMC Bhavan, Shivaji Nagar, Pune'),
('Late Baburao Genba Shewale Hospital, Chikhalwadi', ', Aundh Road, Pune'),
('Late Rohidas Kirad Dispensary, Ganeshpeth', ', Ganesh Peth, Pune'),
('Late Damodarraoji Galande Patil Dispensary, Kalyani Nagar', ', Kalyani Nagar, Pune'),
('Christ Rock Edward Paul Dispensary, Lohagaon', ', Lohagaon, Pune'),
('Ga.Bha. Indumati Manilal Khanna Dispensary, Maharshi Nagar', ', Maharshi Nagar, Gultekdi, Pune'),
('Rajashree Shahu Maharaj Dispensary, Bhim Nagar - Shirke Wasti', ', Bhim nagar, Pune'),
('Late Sundarabai Ganpat Raut Dispensary, Kelewadi', ', Kelewadi, Pune'),
('Late Lokshahir Annabhau Sathe Dispensary, Gandhi Nagar', ', Gandhi Nagar, Pune'),
('Dr. Kotnis Health Centre, Gadikhana', ', Gadikhana, Shukruwar Peth, Pune'),
('Late Bapu Saheb Genuji Kawade Patil Dispensary,  Kawade Wasti, Koregaon Park', ', Koregaon Park, Pune'),
('Kalas Dispensary, Jadhav Wasti - Kalas', ', Kalas, Pune'),
('Bharatratna Dr. Babasaheb Ambedkar Dispensary, Dias Plot', ', Dias Plot, Pune'),
('Late Dashrath Baliram Bhangire Disp., Mohammad Wadi', ', Mohammad Wadi, Pune'),
('Chatrapati Shahu Maharaj Disp., Kedari Nagar, Wanawadi', 'Wanowrie - Ramtekdi WO, Kedari Nagar, Wanowrie, Pune'),
('Late Bartakke Disp., Atul Nagar', ', Atul Nagar, Pune'),
('Janta Vasahat Dispensary, Janta Vasahat', ', Janta vasahat, Pune'),
('Yug Purush Raja Shiv Chatrapati, Bibwewadi (Upper) Disp.', ', Upper Bibwewadi, Pune'),
('Late Bindu Madhav Thakare Disp. Gosavi Wasti', 'Kothrud - Bavdhan WO, Gosavi Wasti, Kothrud, Pune'),
('PMC Vadagaon Disp., Dhayari', 'Sinhagad Road WO, Vadgaon, Pune'),
('Late Vilasrao Tambe Disp Dhankawadi', 'Sahakar Nagar - Dhankawadi WO, Dhankawadi, Pune'),
('Late Pruthak Barate Disp, Ramnagar ', 'Warje - Karve Nagar WO, Ramnagar, Warje, Pune'),
('Late Kalawatibai Todkar Disp., Somaver Peth', ', Somwar Peth, Pune'),
('Ward No.76, Katraj Davakhana', 'Sahakar Nagar - Dhankawadi WO, Sukh Sagar Nagar, Pune'),
('Shri. Sadguru Shankar Maharaj Disp., Bibwewadi', ', Bibwewadi, Pune'),
('Swatantrya Senani Gotiram Bhaiyya Kachi, Guruvar Peth Poly Clinic', ', Guruwar Peth, Pune'),
('Late Murlidhar Pandurang Laygude Disp., Dhayari', 'Sinhagad Road WO, Dhayari, Pune'),
('Swargiya Se Gangaram Karne Disp Shastrinagar Yerwada', 'Sangamwadi WO, Yerawada, Pune'),
('PMC Dispensary, No. 62 Kondhwa Bk.', 'Kondhwa - Yewlewadi WO, Kondhwa, Pune'),
('Late Premchand Oswal Disp. Upper Indirnagar', ', Upper Indira Nagar, Pune'),
('PMC Dispensary Sainagar, Kondhwa', ', Sai nagar, Pune'),
('Late Meena Tai Thakare Polyclinic, Wadgaon Sheri Disp. ', ', Wadgaonsheri, Pune'),
('PMC Dispensary, Kharadi', ', Kharadi, Pune'),
('Hazrat Khwaja Moinuddin Khisti Rahe, Khwaja Garib Nawaz Disp., Mithanagar', ', Mitha Nagar, Pune'),
('E - Health Centre, Laxmi Nagar, Kothrud', 'Kothrud - Bavdhan WO, Laxmi Nagar, Kothrud, Pune'),
('E - Health Centre, Ramtekdi, Hadapsar', 'Wanowrie - Ramtekdi WO, Ramtekdi, Pune'),
('Smart Clinic, Baner', 'Aundh - Baner WO, Baner, Pune'),
('Immunization Centre, Narayan Peth', ', Narayan Peth, Pune'),
('Old Firta Dispensary', ', , Pune'),
('Navin Firta Dispensary', ', , Pune'),
('PMC Firta Dispensary, Ward No.40 Katraj, Vasant More Firta Dispensary', 'Kondhwa - Yewlewadi WO, Katraj, Pune'),
('Mahrashtra Medical Foundation Joshi Hosptial', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sathe Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Dr. Tarabai Limye Hospital', '5, KASBA-VISHRAM, Pune'),
('Dr. Paranjpe Gynac Hospital', '5, KASBA-VISHRAM, Pune'),
('Nanal Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Dr. Deshmukh Hospital', '5, KASBA-VISHRAM, Pune'),
('Hrishikesh Healthcare pvt. Ltd.', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Colony Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Dr. Purandare Maternity Home', '5, KASBA-VISHRAM, Pune'),
('Lokmanya Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Dr. Karve"s Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Yashshree Maternity & Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Sushrut  Hospital ', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Harjeevan Hospital', '5, KASBA-VISHRAM, Pune'),
('Manoj Clinic', '5, KASBA-VISHRAM, Pune'),
('Sanjeevan Surgery/ Atharva Netralaya & Reserch Centre ', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Nerlikars Hospital', '3, SINGHARD ROAD, Pune'),
('Katariya Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Dr. Todkar Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Marathe Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dr. Purohit Maternity Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dwidal Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Gultekdi Nursing Home & Maternity Home', '5, BIBEWADI, Pune'),
('Sushrusha Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Poona Advantist Hospital', '5, BIBEWADI, Pune'),
('Aliance Munot Hospital', '5, BHAVANI PETH, Pune'),
('Sharada Clinic', '5, BHAVANI PETH, Pune'),
('Anand Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Sharada Clinic           Shaishav Clinic', '5, KASBA-VISHRAM, Pune'),
('ENT Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Surgical Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Sutika Seva Mandir', '5, KASBA-VISHRAM, Pune'),
('Naik Orthopadic Hospital', '5, KASBA-VISHRAM, Pune'),
('Ratnadeep  Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Kering Hospital', '5, BHAVANI PETH, Pune'),
('Mahatma Gandhi Hospital', '5, KASBA-VISHRAM, Pune'),
('Dr.Patankar Medical Foundetion & Patankar Hospital Pvt. Ltd.', '5, KASBA-VISHRAM, Pune'),
('Deshmukh Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Jijamata Hospital', '5, KASBA-VISHRAM, Pune'),
('Mulanche Navjeevan Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Shreeyash Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Yashraj Nursing Home', '5, BIBEWADI, Pune'),
('Wagdarikar Hospital', '5, KASBA-VISHRAM, Pune'),
('Vartak Health Services pvt. Ltd.', '3, WARJE-KARVENAGAR, Pune'),
('Madhavrao Rande Memorial Hospital (Sanjivan Hospital)', '3, WARJE-KARVENAGAR, Pune'),
('Anand Maternity & Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Gokhale Hospital', '5, KASBA-VISHRAM, Pune'),
('Suyash Hospityal', '2, KOTHRUD-BAVDHAN, Pune'),
('Pooja Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dr. Ranade Hospital ', '5, KASBA-VISHRAM, Pune'),
('Asha Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Lathi Hospital & Surgical Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Kalekar Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Godbole Hospital ', '5, KASBA-VISHRAM, Pune'),
('Matruseva Hospital Maternity & Surgical Nursing Home', '1, DHOLE-PATIL ROAD, Pune'),
('Shanta Clinic', '4, WANADI-RAMTEKDI, Pune'),
('Nachiket Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Surya Hospital pvt.ltd. Surya sahaydri hospital', '5, KASBA-VISHRAM, Pune'),
('Kelkar Pediatric Hospital     ( Children )', '5, KASBA-VISHRAM, Pune'),
('Dhodu Mama Sathe Hospital Vaidykiya Mahavidyalaya', '3, WARJE-KARVENAGAR, Pune'),
('Sancheti Institute for Orthopedic & Rehabilitaion', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Bapat Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Shintre Hospital', '5, KASBA-VISHRAM, Pune'),
('Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Dhanwantari Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Vinayak Hospital Maternity Nursing Home & Vinayak Homopatic Clinic', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Amey Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Poona Hospital & Reasarch Center', '5, KASBA-VISHRAM, Pune'),
('Deodhar Eyes Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Devyani Hospital Surguri Maternity & General Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Niramay Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Dr. Khurd Maternity Home', '5, KASBA-VISHRAM, Pune'),
('Sanjeevani Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Mamata Maternity Nursing Home', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Maher CLINIC', '2, KOTHRUD-BAVDHAN, Pune'),
('Jehangir Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Phadnis Hospital Maternity & General Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Deendayal Memorial Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sahwas Hospital Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Komal  Nursing Home & Shetiya Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Asha Kiran Hospital', '5, KASBA-VISHRAM, Pune'),
('Kothari Hospital', '5, SAHAKARNAGAR-DHANKWADI, Pune'),
('Bora Nursing Home', '5, BHAVANI PETH, Pune'),
('Suraj Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Suman Polyclinic & Nursing Home Pediatric & Medical', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Tupe Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Sadhu Vaswani Mission Medical Complex  (inlax & Budhrani Hospital)', '1, DHOLE-PATIL ROAD, Pune'),
('N.M.Wadiya Institute of Cardiology Charitable Trust', '1, DHOLE-PATIL ROAD, Pune'),
('Sardesai Hospital & ENT Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Dr. Vaidya Hospital Surgical & General Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Dabake Maternity & General Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Krishna Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Ghaisas ENT Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sarswati Vilas Hospital', '5, KASBA-VISHRAM, Pune'),
('Rukhmini Hospital', '5, BIBEWADI, Pune'),
('Dr. Khanade Hospital', '5, BIBEWADI, Pune'),
('Swanand Maternity Hospital & Laboretary', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Childrens Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Om Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Mahajan Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Sant Clinic Gaynic & Maternity Home. (Strirog & prasuti Shashtra Hospital)', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Rode Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Potdar Maternity Home Obstetric & Gayncology & Pediyatric Speacility', '3, SINGHARD ROAD, Pune'),
('Zanwar Eye Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Chinmay Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Shreyas Maternity Home', '3, WARJE-KARVENAGAR, Pune'),
('Marathe Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Gupte hospital of acurate daigonestic pvt.ltd.', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sadhana Hospital & General Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Kamal Nursing Home', '5, BIBEWADI, Pune'),
('Joshi Hospital Maternity & Gaynic Hospital', '5, BIBEWADI, Pune'),
('Akshay Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Chaitanya Nursing Home', '4, WANADI-RAMTEKDI, Pune'),
('Maharashtra Medical Foundetion Ratna Memorial Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Kamal Netra Rugnalya', '2, KOTHRUD-BAVDHAN, Pune'),
('Deodhar Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Sushrut Narsing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Anand Hospital', '5, BIBEWADI, Pune'),
('Bhide Hospital Balrog Vibhag', '5, KASBA-VISHRAM, Pune'),
('Krushna Hospital & Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Agarwal Nursing Home & General Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Ashwini Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Manu Eye Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Shri. P.P.Loknath TirthSwami Maharaj Smarak Shri. Tuljabhavani Aarogya Dham', '3, WARJE-KARVENAGAR, Pune'),
('Shraddha Hospital ', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Kotbagi  Hospital Pvt. Ltd.', '2, AUNDH-BANER, Pune'),
('Dr. Gaikwad Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Kushte Nursing Home Maternity & General Surgical Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Shri Hospital Nursing', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Suman Sargical Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Kale Hospital', '5, BIBEWADI, Pune'),
('Dhanwantari Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Shaikh  Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Dr. Purohit Nursing Home', '5, BIBEWADI, Pune'),
('Dr. Nenes Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Vastalya Nursing Home', '3, SINGHARD ROAD, Pune'),
('Deep  Eye Clinic ', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Yogesh Hospital', '5, KASBA-VISHRAM, Pune'),
('Shreyash Maternity & Eye Hospital', '2, AUNDH-BANER, Pune'),
('Omkar Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Walvekar Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Kelkar Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Latkar Hospital', '2, AUNDH-BANER, Pune'),
('Siddharth Hospital', '5, BIBEWADI, Pune'),
('Shri J. Hospital', '5, BIBEWADI, Pune'),
('Orthopedic Nursing Home', '4, WANADI-RAMTEKDI, Pune'),
('Dr. Wachasunder ENT Clinic', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('PETELS HOSPITAL', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Indira Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Dr. Sabane Prasuti & Shushrusha Gruh', '2, KOTHRUD-BAVDHAN, Pune'),
('Anup Hospital', '3, SINGHARD ROAD, Pune'),
('Kelkar Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Nirmal  Memorial Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Umarji Hospital', '5, KASBA-VISHRAM, Pune'),
('Bhave Nursing Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Mathura Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Date Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Phadke Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Remedy Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Purunanda Sargical Clinic', '4, KONDHWA-YEVALEWADI, Pune'),
('Navjeevan Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Parasnis Hospital', '5, BIBEWADI, Pune'),
('Aarogya Seva Medical Academy  of India Charitable Trust & ACE Hospital ( Multi Speciality Care )', '3, WARJE-KARVENAGAR, Pune'),
('Gandhi Accident & General Hospital', '5, KASBA-VISHRAM, Pune'),
('Gaikwad Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Shushrut Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Sakhi Clinic', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sarpotdar Eye Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Akshay Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Kulkarni Endo Surgery  Institute & Reconstructive  Urology  Center', '2, KOTHRUD-BAVDHAN, Pune'),
('Srujan Maternity & Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Joglekar Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Karne Hospital Pvt. Ltd. Orthopedic Nursing Home', '5, BIBEWADI, Pune'),
('Dr. Pai Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Pramodini Urology Foundiation & Stree Clinic', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Siddhant Maternity Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dr. Tekwade Eye Hospital', '5, BIBEWADI, Pune'),
('Date Hospital', '5, KASBA-VISHRAM, Pune'),
('Swyam Clinic & Nursing Home', '5, BHAVANI PETH, Pune'),
('Kulkarni Hospital & Child Hospital & Prasutigruh', '5, KASBA-VISHRAM, Pune'),
('Suryaprabha Nursing Home & ENT Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Chandak Hospital', '5, KASBA-VISHRAM, Pune'),
('Dr. Patwardhan Hospital & Prasutigruha', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dr. Talesara  Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Anand Medical Foundetion & Subuodh Hospital & Resarch Center', '2, KOTHRUD-BAVDHAN, Pune'),
('Satyanand  Hospital ', '4, KONDHWA-YEVALEWADI, Pune'),
('Aashtang Ayurved Rugnalaya', '5, KASBA-VISHRAM, Pune'),
('Vaibhav General Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Dr. Telang Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Mother Home  Fartility Clinic', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Vivekanand Medical Foundetion Under Dr. Khenat Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Dr. Bhagli Clinic', '5, BIBEWADI, Pune'),
('Dr. Bhagli Nursing Home', '5, BIBEWADI, Pune'),
('Shatau Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Niramay Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Sneha ENT Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Sayali Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Kamla Devi Memorial Hospital', '3, SINGHARD ROAD, Pune'),
('Vimal Nursing Home', '4, KONDHWA-YEVALEWADI, Pune'),
('Pawar Multispeciality Hospital & dignostic Centre Pvt.Ltd.', '4, KONDHWA-YEVALEWADI, Pune'),
('Madhukar General Hospital', '3, SINGHARD ROAD, Pune'),
('Mulye Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Todkar Hospital', '5, BHAVANI PETH, Pune'),
('Parvati Netra Chikitsalya', '5, KASBA-VISHRAM, Pune'),
('Yashwant Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Suyash Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Kamat Clinic', '2, KOTHRUD-BAVDHAN, Pune'),
('Jagtap Hospital', '3, SINGHARD ROAD, Pune'),
('Manohar Prasuti Gruha', '5, BHAVANI PETH, Pune'),
('Modern ENT Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Gadkari Eye Center', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Dhadfale Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Dhruvis  Clinic', '5, KASBA-VISHRAM, Pune'),
('Joshi Maternity Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Bhandari Maternity & Nursing Home', '3, SINGHARD ROAD, Pune'),
('Adate General Hospital', '3, SINGHARD ROAD, Pune'),
('Sathe Maternity Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Deshmukh Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Kamal Nursing Home & Maternity Home', '4, WANADI-RAMTEKDI, Pune'),
('Prakash Eyes Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sanjeevani Hospital', '3, WARJE-KARVENAGAR, Pune'),
('ENT & Eyes Hospital ( Sant Hospital )', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Aawari Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Kidny & Dialysis  Center ( Ambike Hospital )', '2, KOTHRUD-BAVDHAN, Pune'),
('Sham Nursing Home', '3, SINGHARD ROAD, Pune'),
('Dharmadhikari Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Eye Hospital ( Dr. Bhats Eye Care Center )', '5, KASBA-VISHRAM, Pune'),
('K.E.M. Hospital', '5, BHAVANI PETH, Pune'),
('vatsal Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Samarth Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Shri Sai Sneh Diagnostic  Center Pvt. Ltd.', '4, KONDHWA-YEVALEWADI, Pune'),
('Maher Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('N.M.Wadia Hospital', '5, KASBA-VISHRAM, Pune'),
('Chaitanya Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Belsare ENT Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Bhalerao Prasuti Gruha', '4, HADAPSAR-MUNDHWA, Pune'),
('Dr. S.D.Patil Eye Clinic & Hospital', '5, KASBA-VISHRAM, Pune'),
('Suvidha Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Kumbhare Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Kurtkoti Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Dr. Kashyap Nursing Home', '5, BIBEWADI, Pune'),
('Purohit Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Panchsheel Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Paras Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dr. Parkhi Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Vyanketesh  General Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Modern Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('G.M.Babubhai Memorial Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Ranka Medical Foundetion, Ranka Hospital', '5, BIBEWADI, Pune'),
('Salunke Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Sanjeev Maternity & Surgical Hospital', '2, AUNDH-BANER, Pune'),
('Kedarnath Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Kirad Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Jeevan Deep Medicare  Center', '2, AUNDH-BANER, Pune'),
('Shri Samrath Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('PBMAS H.V.Desai Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Prabhudesai Eye Clinic', '5, KASBA-VISHRAM, Pune'),
('Bhagirathi Child Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Inam Hospital Charitable Trust', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Gujrathi Clinic', '5, KASBA-VISHRAM, Pune'),
('Usha Kiran Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Sadguru Nursing Home', '3, SINGHARD ROAD, Pune'),
('Patil Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Family Planning Association of India, Pune', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('M/s. Prachiti Hospital & Resarch Center', '3, SINGHARD ROAD, Pune'),
('Deenannath Mangeshkar Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Girija Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Anusaya Hospital', '4, WANADI-RAMTEKDI, Pune'),
('Yashwant Hospital', '3, SINGHARD ROAD, Pune'),
('Chinmay Nursing Home ', '5, KASBA-VISHRAM, Pune'),
('Bakshi Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Gayatri Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Ashwini Nursing Home & Maternity Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Dr. Konkar Nursing Home', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Nande Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Ajinkya Nursing Home', '2, AUNDH-BANER, Pune'),
('Pandit Clinic', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Alatkar Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Wankhede Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Shah  Accident  Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Life Line Hospital', '2, AUNDH-BANER, Pune'),
('Sangam Hospital', '5, BIBEWADI, Pune'),
('Children Hospital', '5, KASBA-VISHRAM, Pune'),
('Bidkar Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Patil Hospital', '3, SINGHARD ROAD, Pune'),
('Padalkar Pediatric & Nionetal Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Todmal Nursing Home', '1, DHOLE-PATIL ROAD, Pune'),
('Yashoda Nursing Home', '2, AUNDH-BANER, Pune'),
('Harsh Hospital', '5, BIBEWADI, Pune'),
('Polyclinic & Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Medipoint Hospital', '2, AUNDH-BANER, Pune'),
('Kasturba Speciality Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Mother Care Clinic Nursing Home', '4, BIBEWADI, Pune'),
('Dharma Orthopedic Center', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Badve Maternity & Nursing Home', '1, DHOLE-PATIL ROAD, Pune'),
('Niranjan Nursing Home', '5, KASBA-VISHRAM, Pune'),
('Kulkarni Hospital & Daigonostic Center', '3, WARJE-KARVENAGAR, Pune'),
('Bumb Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Mantri Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Nayan Jyot Eye Clinic & Lesar Center', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Amit Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Pramila Care Center', '3, WARJE-KARVENAGAR, Pune'),
('Shahade Hospital', '5, KASBA-VISHRAM, Pune'),
('Trimurti Hospital', '3, SINGHARD ROAD, Pune'),
('Aadarsh Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Senses ENT Hospital & Clinic', '3, KOTHRUD-BAVDHAN, Pune'),
('Agarwal Maternity & General Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Nobal Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Rakshak Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Chaitanya Hospital & Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Surya Netralaya', '2, AUNDH-BANER, Pune'),
('Vimal Hospital', '5, BHAVANI PETH, Pune'),
('Chaitanya Hospital General Medicin Hospital', '3, SINGHARD ROAD, Pune'),
('Dr. Sarode Nursing Home', '2, AUNDH-BANER, Pune'),
('Birajdar Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Sandip Wagh Eye Center', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('C.D.C. & Center for Laproscopy Surgery', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Shri Sainath Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Eye Care Center', '3, WA, Pune'),
('Sirin  Hospital Pvt. Ltd.', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Sunita Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Day Care  Orthopedic Hospital', '5, KASBA-VISHRAM, Pune'),
('Prakash Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Disha Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Chaitanya Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Capital Polyclinic Health Hospital', '3, SINGHARD ROAD, Pune'),
('Kaluskar Hospital & Laboretory', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Shri Samrath Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Borse Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Vaibhavi Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Unity Ortho & Eyes Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('High-Line Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Machve Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Mehta Nursing Home', '5, BIBEWADI, Pune'),
('Ganga Nursing Home', '1, DHOLE-PATIL ROAD, Pune'),
('Konkan Mitra Mandal Trust"s Sahyadri  super Speciality Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Paranjpe Eye Clinic & Surgery Center', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sindhu Nursing Home', '2, KOTHRUD-BAVDHAN, Pune'),
('Sai nursing Home', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Ashirwad Hospital', '3, SINGHARD ROAD, Pune'),
('Accurate Diagnostic Pvt. Ltd.', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Suyash Nursing Home & General Nursing Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Shri Datta Hospital & Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Divya Clinic', '2, AUNDH-BANER, Pune'),
('Gurukrupa Maternity Home', '3, SINGHARD ROAD, Pune'),
('Dugad Hospital', '5, BIBEWADI, Pune'),
('Bharti Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Nikhil polyclinic', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Anand eye care', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Shri Sainath Ho spital', '1, SAHAKARNAGAR-DHANKWADI, Pune'),
('Aadarsh Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Parmar Hospital', '2, AUNDH-BANER, Pune'),
('Shrisai Prasad Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Londhe Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Chintamani Hospital', '5, BIBEWADI, Pune'),
('Rutu Anand Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Yashraj Nursing Home', '4, KONDHWA-YEVALEWADI, Pune'),
('Bidaye Hospital pvt.ltd.', '5, KASBA-VISHRAM, Pune'),
('Mankar children & eye hospital', '3, SINGHARD ROAD, Pune'),
('Deccan Center', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('anand hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dr. Gogate  eye clinic', '1, DHOLE-PATIL ROAD, Pune'),
('vinayak netralaya', '2, KOTHRUD-BAVDHAN, Pune'),
('City hospital & daigonestic center', '5, BHAVANI PETH, Pune'),
('Dr. jadhav eye foundetion resarch & devolapment center', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('khare eye institute', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('sahyadri hospital , Kothrud', '2, KOTHRUD-BAVDHAN, Pune'),
('Dr. bande hospital', '5, BIBEWADI, Pune'),
('prashant hospital maternity & general hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('sunny  nursing home', '2, KOTHRUD-BAVDHAN, Pune'),
('saideep eye hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Trimal Hospital', '5, BIBEWADI, Pune'),
('dr. pabalkar nursing home', '5, KASBA-VISHRAM, Pune'),
('vatsalya  children hospital', '4, WANADI-RAMTEKDI, Pune'),
('Healthplus nursing home', '2, AUNDH-BANER, Pune'),
('Shraddha Hospital ', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('pratibha nursing home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Mantri Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Nobel  Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('chavan nursing home', '5, KASBA-VISHRAM, Pune'),
('punrvasu chikitsalaya', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('suraj hospital', '5, BIBEWADI, Pune'),
('shashwat health pvt.ltd shashwat Hospital.', '2, KOTHRUD-BAVDHAN, Pune'),
('Anand hospital', '3, WARJE-KARVENAGAR, Pune'),
('k.k. hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('amrut hospital', '1, DHOLE-PATIL ROAD, Pune'),
('sane guruji aarogya kendra', '4, HADAPSAR-MUNDHWA, Pune'),
('shushurt multi -speciality  hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('kumbhare hospital', '1, DHOLE-PATIL ROAD, Pune'),
('yashwant eye clinic & hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('sapna clinic', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('chandralok hospital', '5, BIBEWADI, Pune'),
('The eye foundetion', '5, KONDHWA-YEVALEWADI, Pune'),
('Oyster  & pearl hospital pvt.ltd.', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Ayodhya chaitrtable trust, ayodhya general hospital', '4, WANADI-RAMTEKDI, Pune'),
('indian red cross soc. Nursing home', '5, BHAVANI PETH, Pune'),
('Ramkrishna  hospital', '5, KASBA-VISHRAM, Pune'),
('center for joint repleacment surgary', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Rakhi nursing home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Samarth Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Mohan ent clinic', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('medileser - vision correction center', '2, KOTHRUD-BAVDHAN, Pune'),
('Rahi health care', '5, BIBEWADI, Pune'),
('sahydri hospital ltd. Sahyadri Hospital, Bibvewadi', '5, BIBEWADI, Pune'),
('Manswardhan diduction rehabliation mental health', '2, AUNDH-BANER, Pune'),
('varadvinayak hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('shri balaji eye hospital', '5, BIBEWADI, Pune'),
('Dhanwantari hospital', '5, BHAVANI PETH, Pune'),
('yashashree  hospital', '5, BIBEWADI, Pune'),
('Meera hospital', '5, BHAVANI PETH, Pune'),
('Vinayak Hospital', '5, BIBEWADI, Pune'),
('inamdar hospital ( c.i.m.e.t.)', '4, WANADI-RAMTEKDI, Pune'),
('Bliz fertility center & pune center for womens health', '1, DHOLE-PATIL ROAD, Pune'),
('aabane hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('aakankasha eye clinic day care center', '4, WANADI-RAMTEKDI, Pune'),
('Dr. Sada multi specality hospital', '5, BIBEWADI, Pune'),
('Lata Mangeshkar Medical Foundation"s Mai Mangeshkar Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Apurva panchkarma center', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('shotri nursing home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('prathmesh Accident & orthopedic Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('s.p.deshpande eye clinic', '5, KASBA-VISHRAM, Pune'),
('om hopital', '2, AUNDH-BANER, Pune'),
('Dr. chitale ent hospital', '5, KASBA-VISHRAM, Pune'),
('omkar hospital', '3, SINGHARD ROAD, Pune'),
('ganga maternity & general hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Renu hospital', '2, AUNDH-BANER, Pune'),
('Oyster  & pearl Tulip  hospital ', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Gujar children hospital', '5, BIBEWADI, Pune'),
('vibhute hospital', '5, KASBA-VISHRAM, Pune'),
('skin citi hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Medipoint hospital', '1, DHOLE-PATIL ROAD, Pune'),
('ayris eye care', '3, WARJE-KARVENAGAR, Pune'),
('prakash netralaya', '2, AUNDH-BANER, Pune'),
('shri maternity & nursing home', '3, WARJE-KARVENAGAR, Pune'),
('kohkade hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('parvati general hospital', '5, KASBA-VISHRAM, Pune'),
('vinod memorial multispeciality hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('chinchnikar orthopedic & maternity center', '3, SINGHARD ROAD, Pune'),
('Lifeline multispecaity Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Bhide hospital orthopedic divission', '5, KASBA-VISHRAM, Pune'),
('Rakshak multi specility hospital', '3, SINGHARD ROAD, Pune'),
('universal hospital', '5, KASBA-VISHRAM, Pune'),
('vardhman eye care ', '5, BIBEWADI, Pune'),
('LOC HEALTHCARE LLP', '5, KASBA-VISHRAM, Pune'),
('netra seva kendra ( jan kalyan eye bank )', '5, KASBA-VISHRAM, Pune'),
('rao nursing home', '5, BIBEWADI, Pune'),
('shendkar health care  hospitality services pvt. Ltd. Global Hospital & Reserch Institute', '3, SINGHARD ROAD, Pune'),
('adkar hospital & resarch institute pvt.ltd.( sai shree hospital )/ Orthopedic Centre', '2, AUNDH-BANER, Pune'),
('shri eye & dental clinic', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Naik nimbalkar hospital ( day - care eye hospital )', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('kumbhare clinic & nursing home', '1, DHOLE-PATIL ROAD, Pune'),
('emrald endoscopy center', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Grant medical foundetion Ruby Holl Clinic', '1, DHOLE-PATIL ROAD, Pune'),
('galaxcy care laproscopy institute pvt. Ltd.', '3, WARJE-KARVENAGAR, Pune'),
('shivneri hospital', '3, KONDHWA-YEVALEWADI, Pune'),
('dr. manohar joshi memorial hospital (M.J.M. Hospital)', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Ishwar krupa nursing home', '5, BIBEWADI, Pune'),
('sidhhi hospital laproscopy center', '4, KONDHWA-YEVALEWADI, Pune'),
('wadekar nursing home ( maternity  &  ENT home  )', '3, SINGHARD ROAD, Pune'),
('Aims hospital & resarch center', '2, AUNDH-BANER, Pune'),
('kala clinic & nursing home', '4, KONDHWA-YEVALEWADI, Pune'),
('shaswat hospital ( aundh )', '2, AUNDH-BANER, Pune'),
('Dyandeep general hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Devshri Hospital ', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Suyog Narsing Home Pra. Ltd. ', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Parivartan Ayurved Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Grant medical foundetion Ruby Holl Clinic- wanovari', '4, WANADI-RAMTEKDI, Pune'),
('Ashswin Hospital', '5, KASBA-VISHRAM, Pune'),
('Ashirvad ENT And Maternity Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Chandan Nagar Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Saikrupa Narsing Home', '5, KASBA-VISHRAM, Pune'),
('Yashda Hospital', '5, KASBA-VISHRAM, Pune'),
('Parvati Ganral Hospital', '5, SAHAKARNAGAR-DHANKWADI, Pune'),
('Famili Planing Asociation Of India, Pune', '2, KOTHRUD-BAVDHAN, Pune'),
('Contacare Eye Hospital', '3, KOTHRUD-BAVDHAN, Pune'),
('shivam hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Life Care Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Kolambia Ashia Hospital Pr. Ltd.', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Devyani Multy Speciality Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Dhanwantari Clinic', '4, KONDHWA-YEVALEWADI, Pune'),
('Sahyadri Hospitals Ltd.-Sahyadri Super Speciality Hospital (Nagar Road)', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Kalyani Hospital ', '5, KASBA-VISHRAM, Pune'),
('Chandrama Clinic', '5, KASBA-VISHRAM, Pune'),
('Lodha Hospital And Maternity Home', '3, WARJE-KARVENAGAR, Pune'),
('nayantara eye clinic', '2, KOTHRUD-BAVDHAN, Pune'),
('pharande eye hospital & phaco center', '3, SINGHARD ROAD, Pune'),
('sheth tarachand ramanath charitable aurvedic hospital', '5, BHAVANI PETH, Pune'),
('bharti ayurved hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Datar Hospital', '2, AUNDH-BANER, Pune'),
('Vision next', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Vision Eye Center', '2, KOTHRUD-BAVDHAN, Pune'),
('Janani Nursing Home ', '2, KOTHRUD-BAVDHAN, Pune'),
('Chhaya Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Gurdeo Nursing Home', '3, SINGHARD ROAD, Pune'),
('Matruchaya Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Aadhar Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Contacare Eye Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Bharti Homeopathic Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Dhanwantari Hospital', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Lokmanya hospital Pvt. Ltd.', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Shatayu Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Meera Matrnity & General Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Atharv Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Sarwat Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Navjeevan Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Tanmay Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Shantalaxmi Clinic', '5, KASBA-VISHRAM, Pune'),
('Dr. Bhange''s Eye Day Care Center', '5, KASBA-VISHRAM, Pune'),
('Gold Rush Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Modi Clinic', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Mrunmayee Health Cear pvt. Ltd. ( sangamnerkar Hospital )', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Sharad Hospital', '3, SINGHARD ROAD, Pune'),
('Pearl womens hospital & yash IVF`', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Samarth Nursing Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Vinayak Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Anup Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Prabhudesai Eye Clinic', '3, KOTHRUD-BAVDHAN, Pune'),
('Adnya Clinic & Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Lotus Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Gems Hospital & Enodoscopy Center', '3, KOTHRUD-BAVDHAN, Pune'),
('Shree Nursnig Home', '3, WARJE-KARVENAGAR, Pune'),
('Zed Plus Accident Hospital & Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Shree Gurudatta Specaility Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Siddiqua Hospital & Nursing Home', '4, KONDHWA-YEVALEWADI, Pune'),
('Pioneer Medilesar Pvt. Ltd.', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Pune Netraylaya', '2, AUNDH-BANER, Pune'),
('Vastalya Hospital', '5, KASBA-VISHRAM, Pune'),
('Om Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('CT Nursing Home', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Kalyani Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Nova Pluse IVF Clinic Pvt. Ltd.', '5, KASBA-VISHRAM, Pune'),
('Ameya Nursing Home', '1, YERAWADA-KALAS-DHANORI, Pune'),
('SUMITRA PARALYSIS CARE CENTRE', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Poona Leasar Center', '3, WARJE-KARVENAGAR, Pune'),
('Neo Hospital', '5, KASBA-VISHRAM, Pune'),
('Noble Hospital-', '4, HADAPSAR-MUNDHWA, Pune'),
('Shraddha Nursing Home', '3, SINGHARD ROAD, Pune'),
('Om Nursing Home', '3, SINGHARD ROAD, Pune'),
('Sai Netralay & specality Clinic', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('kids clinic (I) pvt. Ltd.cloud Cline  nine Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Hope Nursing Home', '1, DHOLE-PATIL ROAD, Pune'),
('Speciality Day care Centre', '2, KOTHRUD-BAVDHAN, Pune'),
('Zenith Medicare Pvt. Ltd.', '4, HADAPSAR-MUNDHWA, Pune'),
('Kirad Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Kamalnayan Nursing Home/Hospital', '5, KASBA-VISHRAM, Pune'),
('shree Hospital Criticare & Trauma Centre Pvt.Ltd.', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Chaitanya Eye Clinic & phaco centre', '5, KASBA-VISHRAM, Pune'),
('Apolo Speciality Hospitals Pvt. Ltd.', '5, KASBA-VISHRAM, Pune'),
('Welfare Medical Foundation"s Willoo Poonawala Memorial Hopstial', '4, HADAPSAR-MUNDHWA, Pune'),
('Indira IVF Hospital pvt. Ltd.', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Ashwini Hospital', '2, AUNDH-BANER, Pune'),
('Bansal Medical Foundation', '1, DHOLE-PATIL ROAD, Pune'),
('Healing Hands Clinic Pvt. Ltd.', '5, KASBA-VISHRAM, Pune'),
('Ashtang Ayurved Rugnalaya', '5, KASBA-VISHRAM, Pune'),
('Asthetic Medispa Pvt. Ltd. (Day-care)', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Umarji mother & child care', '2, AUNDH-BANER, Pune'),
('Sanjivan Hospital', '2, AUNDH-BANER, Pune'),
('Vighnaharta Hospital', '5, BIBEWADI, Pune'),
('Bavdhan medicare center', '2, KOTHRUD-BAVDHAN, Pune'),
('ELPIS IVF & Maternity Home', '2, AUNDH-BANER, Pune'),
('Unity Hospital', '2, AUNDH-BANER, Pune'),
('National Institute of Ophalmology (Neo Aundh)', '2, AUNDH-BANER, Pune'),
('Sagar Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Vimal Nursing Home', '2, AUNDH-BANER, Pune'),
('Eva Nursing Home', '3, SINGHARD ROAD, Pune'),
('Moraya Nursing Home LLP', '4, KONDHWA-YEVALEWADI, Pune'),
('Healing Hands Clinic Pvt. Ltd.', '1, DHOLE-PATIL ROAD, Pune'),
('Balaji Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Prerana Nursing Home', '4, KONDHWA-YEVALEWADI, Pune'),
('Kids clinic (I) pvt. Ltd. cloud nine Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Kurkute Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Tepan Memorial Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Siddharth Nursing Home', '3, WARJE-KARVENAGAR, Pune'),
('Sai nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Chandra Nursing Home', '4, KONDHWA-YEVALEWADI, Pune'),
('Siddhivinayak Hopital', '4, KONDHWA-YEVALEWADI, Pune'),
('Aisan Eye Hospital & laser Institute', '1, DHOLE-PATIL ROAD, Pune'),
('Maheshwari Multispeciality Healthcare & Reserch centre LLP', '4, HADAPSAR-MUNDHWA, Pune'),
('CT Nursing Home          (Unit-2)', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Dhanwantari Hospital', '2, AUNDH-BANER, Pune'),
('Usha Maternity Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Patil Multispeciality Hospital & Laproscopy Center', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Akash Eye Clinic & laser Centre', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Damale skin Clinic', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Nakhare Clinic', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Adakar Hospital & Reserch Institutes, Saishree Hospital', '2, AUNDH-BANER, Pune'),
('Kamat hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Jadhav kids Hospital/ Dr. Jadhav Lahan Mulanche Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('APS Nursing Home', '4, HADAPSAR-MUNDHWA, Pune'),
('Prakash Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('shashwat Hospital (Medical Wing)', '2, KOTHRUD-BAVDHAN, Pune'),
('"18.52 North" Centre For Hand & wrist surgery', '5, BHAVANI PETH, Pune'),
('Nucare Hospital', '2, AUNDH-BANER, Pune'),
('OM Eye Care', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Axix Eye Clinic', '2, KOTHRUD-BAVDHAN, Pune'),
('Jupiter Lifeline Hospitals Ltd.', '2, AUNDH-BANER, Pune'),
('Rising Medicare Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('New Pune Hospital & Nursing Home', '4, KONDHWA-YEVALEWADI, Pune'),
('Dhande Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('Vaibhav Nursing Home', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Ingale womens Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Walimbe Eye Clinic', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Chintamani Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Shri Nursing Home', '3, SINGHARD ROAD, Pune'),
('Gandhi Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Sanjivani Nurinsg Home', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Poona Eye Care & Pvt. Ltd.', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Namtra Nursing Home', '5, BHAVANI PETH, Pune'),
('chordiya nursing home', '4, KONDHWA-YEVALEWADI, Pune'),
('Royal Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Zanwar Felicity Pvt. Ltd. (Healing Hands Clinic)', '2, AUNDH-BANER, Pune'),
('Blossoms Women Care', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Laxmi Clinic', '5, KASBA-VISHRAM, Pune'),
('Glam-x Aesthetic Centre', '4, HADAPSAR-MUNDHWA, Pune'),
('New Sofiya Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Hi-Tech Eye Surgery & Leser Centre', '4, KONDHWA-YEVALEWADI, Pune'),
('National Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Krishna Prabhu Hospital', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Ashwini Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Pune Fertility Centre', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Pawar Surgical Hospital', '4, HADAPSAR-MUNDHWA, Pune'),
('Om Eye Clinic & laser Centre, Day-care', '5, KASBA-VISHRAM, Pune'),
('Dr. Mhaske Hospital & reserch Centre Pvt. Ltd.', '4, HADAPSAR-MUNDHWA, Pune'),
('Shinde Hospital & Nursing Home', '3, SINGHARD ROAD, Pune'),
('Khade Chinldren Hospital', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Shreeram Eye & Dental Care Centre', '5, BIBEWADI, Pune'),
('Samarth Eye Clinic & Day-Care Centre', '3, SINGHARD ROAD, Pune'),
('Jehangir Speciality Hospital (Unit Of Principal HealthCare & Wellness Pvt. Ltd.', '2, KOTHRUD-BAVDHAN, Pune'),
('Yash Eye Clinic', '2, KOTHRUD-BAVDHAN, Pune'),
('Anuja Hospital', '3, SINGHARD ROAD, Pune'),
('Borikar Hospital', '3, WARJE-KARVENAGAR, Pune'),
('Divya Jyot Hospital', '2, KOTHRUD-BAVDHAN, Pune'),
('sahyadri Hospitals Ltd.-Sahyadri Super Speciality Hospital (Hadpasar)', '4, HADAPSAR-MUNDHWA, Pune'),
('Bhimrao Tidke Patil MultiSpeciality Hospital Pvt. Ltd.', '1, YERAWADA-KALAS-DHANORI, Pune'),
('Poona Preventive Cardiology Centre', '3, SAHAKARNAGAR-DHANKWADI, Pune'),
('Embrio IVF Centre', '2, AUNDH-BANER, Pune'),
('Dr. Dudhbhate Netralaya & Retina Centre', '3, SINGHARD ROAD, Pune'),
('Shatayu Hospital', '3, SINGHARD ROAD, Pune'),
('Dr. Ketkar Nursing Home', '2, SHIVAJINAGAR- GHOLE ROAD, Pune'),
('Deshpande Eye Hospital & Laser Centre', '2, KOTHRUD-BAVDHAN, Pune'),
('Aadhar Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Shree Ayurved & Panchkarma Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Motherhood Hospital ( Rhea Healthcare Pvt. Ltd.', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Jivandhara Multispeciality Hospital', '4, KONDHWA-YEVALEWADI, Pune'),
('Jeevan sparsh Eye Hospital', '5, BIBEWADI, Pune'),
('Shinde Nursing Home & Polyclinic', '5, BHAVANI PETH, Pune'),
('Vatsalya  hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Agarwal"s Healthcare Ltd.', '2, AUNDH-BANER, Pune'),
('Horizon Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Siver Birch MultiSpeciality Hospital pvt. Ltd.', '3, SINGHARD ROAD, Pune'),
('City Care Hospital', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Nityashraddha  Life Care Hospital', '1, DHOLE-PATIL ROAD, Pune'),
('Jeevnjyot Nursing Home', '1, NAGAR ROAD- VADGOANSHERI, Pune'),
('Dr. Pathak Eye Clinic', '3, SINGHARD ROAD, Pune'),
('Bliz fertility center ', '1, DHOLE-PATIL ROAD, Pune'),
('Shree Samarth Hospital', '4, HADAPSAR-MUNDHWA, Pune');
